#!/bin/bash
set +x

export PROJECT_HOME=`cd "$(dirname "$0")"; pwd`

CONFIG="$PROJECT_HOME"/gerar.config
[ -f "$CONFIG" ] || CONFIG=${CONFIG}.exemplo
source "$CONFIG" || exit
source "$COMUM_DIR/funcoes.sh"

mostrar_cabecalho

REMOVER_GERADOS=false
SAIR=false
while [ "$1" ]
do
    case "$1" in
        -a|--ambiente)
            shift
            AMBIENTE=`valida_ambiente $1` || exit $?
            export AMBIENTE
            echo "Ambiente alterado (via linha de comando) para \"$AMBIENTE\""
            ;;
        -r|--remover) REMOVER_GERADOS=true;;
        -s|--sair) SAIR=true;;
        -e|--exportar-keycloak-realm)
            shift
            [ "$1" ] && KEYCLOAK_REALM_NAME=$1
            exportar_keycloak_realm
            exit
            ;;
        -p|--plataforma-alvo)
            shift
            case "$1" in
                Linux|Windows|OSX) :;;
                *) echo "A plataforma alvo \"$1\" é inválida! Suas opções são: Linux, Windows ou OSX!"; exit;;
            esac
            PLATAFORMA_ALVO=$1
            ;;
    esac
    shift
done

d="$PROJECT_HOME/$AMBIENTE"
[ -d "$d" ] || { echo "O diretório \"$d\" não existe!"; exit 1; } 

if [ "$AMBIENTE" = desenvolvimento ]
then
    $REMOVER_GERADOS && remover_gerados "$JBOSS_DESENVOLVIMENTO_DIR"
else
    $REMOVER_GERADOS && remover_gerados
fi

$SAIR && exit

script="$d"/funcoes.sh
[ -f "$script" ] || { echo "O arquivo de funções \"$script\" não está presente!"; exit 1; }
source "$script"

type gerar_${AMBIENTE} &> /dev/null || { echo "A função gerar_${AMBIENTE} não foi encontrada!"; exit 1; }
gerar_${AMBIENTE}
