#!/bin/bash

BASEDIR=`cd "$(dirname "$0")"; pwd`
source "$BASEDIR"/gerar.config &> /dev/null || {
    source "$BASEDIR"/gerar.config.exemplo || exit
}
SQL_DIR=${SQL_DIR:-$BASEDIR/scripts-sql}
SQL_USER=${SQL_USER:-system}
SQL_PASSWORD=${SQL_PASSWORD:-oracle}
SQL_HOST=${SQL_HOST:-localhost}
sql=$SQLCL_HOME/bin/sql

case $1 in
    up|halt|status)
        cd "$DOCKER_ORACLE_XE_HOME"
        vagrant $1
        ;;
    *)
        f="$SQL_DIR"/$1.sql
        [ -f "$f" ] || { echo "Arquivo \"$f\" não encontrado!"; exit 1; }
        $sql -S $SQL_USER/$SQL_PASSWORD@//$SQL_HOST:1521 <<EOF
@"$f"
quit;
EOF
        ;;
esac
