#!/bin/bash

BASEDIR=`cd "$(dirname "$0")"; pwd`
PATCHES_DIR=${PATCHES_DIR:-~/Desktop/gerador-jboss-bpmsuite-keycloak/desenvolvimento/jboss-eap-6.4.files}

cd "$BASEDIR"

echo "Copiando arquivos \"$1\" para \"$PATCHES_DIR\" ..."
for f in $(find . -type f -name "$1")
do
    echo "Copiando $f ..."
    rsync -R $f "$PATCHES_DIR"
done

