#!/bin/bash

BASEDIR=`cd "$(dirname "$0")"; pwd`
COMUM_PATCHES_DIR=${COMUM_PATCHES_DIR:-~/Desktop/gerador-jboss-bpmsuite-keycloak/comum/jboss-eap-6.4.files}
PATCHES_DIR=${PATCHES_DIR:-~/Desktop/gerador-jboss-bpmsuite-keycloak/desenvolvimento/jboss-eap-6.4.files}
DESTINO="$PATCHES_DIR"

cd "$BASEDIR"

echo "Copiando arquivos \"$1\" para \$COMUM_PATCHES_DIR ou \$PATCHES_DIR ..."
for f in $(find . -type f -name "$1")
do
    if [ -f "$COMUM_PATCHES_DIR"/$f ]
    then
        DESTINO="$COMUM_PATCHES_DIR"
    fi

    echo "Copiando $f ... para \"$DESTINO\" ..."
    case $OSTYPE in
        darwin*) rsync -R "$f" "$DESTINO";;
        linux*|cygwin) cp --parents "$f" "$DESTINO";;
    esac
done

